# Network settings
network: "${PUMPBOT_NETWORK:-mainnet}"
rpc_url: "${PUMPBOT_RPC_URL:-}"
ws_url: "${PUMPBOT_WS_URL:-}"
rpc_api_key: "${PUMPBOT_RPC_API_KEY:-}"

# Wallet settings (REQUIRED)
private_key: "${PUMPBOT_PRIVATE_KEY}"

# Trading settings
trading:
  buy_amount_sol: ${PUMPBOT_TRADING_BUY_AMOUNT_SOL:-0.01}
  slippage_bp: ${PUMPBOT_TRADING_SLIPPAGE_BP:-500}
  priority_fee: ${PUMPBOT_TRADING_PRIORITY_FEE:-0}
  auto_sell: ${PUMPBOT_TRADING_AUTO_SELL:-true}
  sell_delay_seconds: ${PUMPBOT_TRADING_SELL_DELAY_SECONDS:-1}
  sell_percentage: ${PUMPBOT_TRADING_SELL_PERCENTAGE:-100.0}
  max_token_age_ms: ${PUMPBOT_TRADING_MAX_TOKEN_AGE_MS:-5000}
  min_discovery_delay_ms: ${PUMPBOT_TRADING_MIN_DISCOVERY_DELAY_MS:-100}

# Strategy settings
strategy:
  type: "${PUMPBOT_STRATEGY_TYPE:-sniper}"
  filter_by_creator: ${PUMPBOT_STRATEGY_FILTER_BY_CREATOR:-false}
  allowed_creators: []
  filter_by_name: ${PUMPBOT_STRATEGY_FILTER_BY_NAME:-false}
  name_patterns: []
  min_liquidity_sol: ${PUMPBOT_STRATEGY_MIN_LIQUIDITY_SOL:-0.0}
  max_tokens_per_hour: ${PUMPBOT_STRATEGY_MAX_TOKENS_PER_HOUR:-10}
  yolo_mode: ${PUMPBOT_STRATEGY_YOLO_MODE:-false}
  hold_only: ${PUMPBOT_STRATEGY_HOLD_ONLY:-false}

# ⚡⚡ ULTRA-FAST MODE - Default and Only Mode
ultra_fast:
  # Core ultra-fast settings (always enabled)
  enabled: true
  skip_validation: ${PUMPBOT_ULTRA_FAST_SKIP_VALIDATION:-false}
  no_confirmation: ${PUMPBOT_ULTRA_FAST_NO_CONFIRMATION:-false}
  fire_and_forget: ${PUMPBOT_ULTRA_FAST_FIRE_AND_FORGET:-false}

  # Parallel processing for maximum speed
  parallel_workers: ${PUMPBOT_ULTRA_FAST_PARALLEL_WORKERS:-3}
  token_queue_size: ${PUMPBOT_ULTRA_FAST_TOKEN_QUEUE_SIZE:-100}

  # Performance optimizations
  cache_blockhash: ${PUMPBOT_ULTRA_FAST_CACHE_BLOCKHASH:-true}
  blockhash_refresh_interval: ${PUMPBOT_ULTRA_FAST_BLOCKHASH_INTERVAL:-10}
  precompute_instructions: ${PUMPBOT_ULTRA_FAST_PRECOMPUTE_INSTRUCTIONS:-true}
  rpc_timeout_ms: ${PUMPBOT_ULTRA_FAST_RPC_TIMEOUT_MS:-3000}

  # Performance monitoring
  benchmark_mode: ${PUMPBOT_ULTRA_FAST_BENCHMARK_MODE:-false}
  log_latency: ${PUMPBOT_ULTRA_FAST_LOG_LATENCY:-true}

  # Risk management for ultra-fast mode
  max_tokens_per_second: ${PUMPBOT_ULTRA_FAST_MAX_TOKENS_PER_SECOND:-10}
  emergency_stop_loss: ${PUMPBOT_ULTRA_FAST_EMERGENCY_STOP_LOSS:--50.0}
  fixed_buy_amount: ${PUMPBOT_ULTRA_FAST_FIXED_BUY_AMOUNT:-true}

  # Advanced optimizations (⚠️ DANGEROUS - use with caution!)
  skip_ata_creation: ${PUMPBOT_ULTRA_FAST_SKIP_ATA_CREATION:-false}
  assume_ata_exists: ${PUMPBOT_ULTRA_FAST_ASSUME_ATA_EXISTS:-false}
  immediate_execution: ${PUMPBOT_ULTRA_FAST_IMMEDIATE_EXECUTION:-true}
  priority_over_safety: ${PUMPBOT_ULTRA_FAST_PRIORITY_OVER_SAFETY:-false}

# JITO MEV Protection Settings
jito:
  enabled: ${PUMPBOT_JITO_ENABLED:-false}
  endpoint: "${PUMPBOT_JITO_ENDPOINT:-https://mainnet.block-engine.jito.wtf/api/v1/bundles}"
  api_key: "${PUMPBOT_JITO_API_KEY:-}"
  tip_amount: ${PUMPBOT_JITO_TIP_AMOUNT:-10000}
  use_for_trading: ${PUMPBOT_JITO_USE_FOR_TRADING:-false}
  confirm_timeout: ${PUMPBOT_JITO_CONFIRM_TIMEOUT:-30}
  max_bundle_size: ${PUMPBOT_JITO_MAX_BUNDLE_SIZE:-5}

# Logging settings
logging:
  level: "${PUMPBOT_LOGGING_LEVEL:-info}"
  format: "${PUMPBOT_LOGGING_FORMAT:-text}"
  log_to_file: ${PUMPBOT_LOGGING_LOG_TO_FILE:-false}
  log_file_path: "${PUMPBOT_LOGGING_LOG_FILE_PATH:-logs/bot.log}"
  trade_log_dir: "${PUMPBOT_LOGGING_TRADE_LOG_DIR:-trades}"

# Advanced settings
advanced:
  max_retries: ${PUMPBOT_ADVANCED_MAX_RETRIES:-3}
  retry_delay_ms: ${PUMPBOT_ADVANCED_RETRY_DELAY_MS:-1000}
  confirm_timeout_sec: ${PUMPBOT_ADVANCED_CONFIRM_TIMEOUT_SEC:-30}
  enable_metrics: ${PUMPBOT_ADVANCED_ENABLE_METRICS:-false}
  metrics_port: ${PUMPBOT_ADVANCED_METRICS_PORT:-8080}

# ========================================
# 🚀 ULTRA-FAST CONFIGURATION EXAMPLES
# ========================================

# 💀 MAXIMUM SPEED (EXTREMELY RISKY):
# export PUMPBOT_ULTRA_FAST_SKIP_VALIDATION="true"
# export PUMPBOT_ULTRA_FAST_FIRE_AND_FORGET="true"
# export PUMPBOT_ULTRA_FAST_PARALLEL_WORKERS="5"
# export PUMPBOT_ULTRA_FAST_PRIORITY_OVER_SAFETY="true"
# export PUMPBOT_STRATEGY_YOLO_MODE="true"

# ⚡ BALANCED ULTRA-FAST (RECOMMENDED):
# export PUMPBOT_ULTRA_FAST_PARALLEL_WORKERS="3"
# export PUMPBOT_ULTRA_FAST_CACHE_BLOCKHASH="true"
# export PUMPBOT_ULTRA_FAST_PRECOMPUTE_INSTRUCTIONS="true"
# export PUMPBOT_ULTRA_FAST_LOG_LATENCY="true"

# 🛡️ ULTRA-FAST + MEV PROTECTION:
# export PUMPBOT_JITO_ENABLED="true"
# export PUMPBOT_JITO_USE_FOR_TRADING="true"
# export PUMPBOT_ULTRA_FAST_PARALLEL_WORKERS="3"

# 🔧 DEVELOPMENT/TESTING ULTRA-FAST:
# export PUMPBOT_ULTRA_FAST_BENCHMARK_MODE="true"
# export PUMPBOT_ULTRA_FAST_LOG_LATENCY="true"
# export PUMPBOT_NETWORK="devnet"

# ========================================
# ⚡⚡ QUICK COMMANDS FOR ULTRA-FAST MODE
# ========================================

# Test ultra-fast mode on devnet:
# ./build/pump-fun-bot --network devnet --dry-run --log-latency

# Ultra-fast with MEV protection:
# ./build/pump-fun-bot --jito --network mainnet

# Maximum speed (DANGEROUS):
# ./build/pump-fun-bot --skip-validation --fire-and-forget --parallel-workers 5

# Benchmark mode:
# ./build/pump-fun-bot --benchmark --log-latency --network devnet

# ========================================
# 📊 EXPECTED PERFORMANCE IMPROVEMENTS
# ========================================

# Ultra-Fast Single:  Discovery → Execution: 20-100ms
# Ultra-Fast Parallel: Discovery → Execution: 5-50ms
# Maximum Speed Mode: Discovery → Execution: 2-20ms

# Parallel Workers Performance:
# 1 worker:  1x speed (baseline)
# 3 workers: 2.5x speed (recommended)
# 5 workers: 3.5x speed (optimal for most setups)
# 10 workers: 4x speed (marginal gains, higher resource usage)

# ========================================
# ⚠️ ULTRA-FAST MODE WARNINGS
# ========================================

# ⚠️ This bot operates in ultra-fast mode by default
# ⚠️ skip_validation can lead to failed transactions
# ⚠️ fire_and_forget doesn't wait for confirmation
# ⚠️ parallel_workers increases resource usage
# ⚠️ priority_over_safety is EXTREMELY DANGEROUS
# ⚠️ Always test on devnet first!
# ⚠️ Monitor your wallet balance closely
# ⚠️ Set reasonable rate limits (max_tokens_per_second)

# 💡 OPTIMIZATION TIPS:
# - Start with 3 parallel workers and tune based on performance
# - Enable latency logging to identify bottlenecks
# - Use benchmark mode for testing optimal settings
# - Combine with Jito for speed + MEV protection
# - Monitor success rates vs speed improvements
# - Adjust RPC timeout based on your connection