# Network settings
network: "${PUMPBOT_NETWORK:-mainnet}"
rpc_url: "${PUMPBOT_RPC_URL:-}"
ws_url: "${PUMPBOT_WS_URL:-}"
rpc_api_key: "${PUMPBOT_RPC_API_KEY:-}"

# Wallet settings (REQUIRED)
private_key: "${PUMPBOT_PRIVATE_KEY}"

trading:
  buy_amount_sol: ${PUMPBOT_TRADING_BUY_AMOUNT_SOL:-0.01}
  buy_amount_tokens: ${PUMPBOT_TRADING_BUY_AMOUNT_TOKENS:-1000000}
  use_token_amount: ${PUMPBOT_TRADING_USE_TOKEN_AMOUNT:-true}
  slippage_bp: ${PUMPBOT_TRADING_SLIPPAGE_BP:-500}
  priority_fee: ${PUMPBOT_TRADING_PRIORITY_FEE:-0}
  auto_sell: ${PUMPBOT_TRADING_AUTO_SELL:-true}
  sell_delay_ms: ${PUMPBOT_TRADING_SELL_DELAY_MS:-1000}
  sell_percentage: ${PUMPBOT_TRADING_SELL_PERCENTAGE:-100.0}
  close_ata_after_sell: ${PUMPBOT_TRADING_CLOSE_ATA_AFTER_SELL:-true}

  # Timing controls
  max_token_age_ms: ${PUMPBOT_TRADING_MAX_TOKEN_AGE_MS:-5000}
  min_discovery_delay_ms: ${PUMPBOT_TRADING_MIN_DISCOVERY_DELAY_MS:-100}

# Strategy settings
strategy:
  type: "${PUMPBOT_STRATEGY_TYPE:-sniper}"
  filter_by_creator: ${PUMPBOT_STRATEGY_FILTER_BY_CREATOR:-false}
  allowed_creators: []
  filter_by_name: ${PUMPBOT_STRATEGY_FILTER_BY_NAME:-false}
  name_patterns: []
  min_liquidity_sol: ${PUMPBOT_STRATEGY_MIN_LIQUIDITY_SOL:-0.0}
  max_tokens_per_hour: ${PUMPBOT_STRATEGY_MAX_TOKENS_PER_HOUR:-10}
  yolo_mode: ${PUMPBOT_STRATEGY_YOLO_MODE:-false}
  hold_only: ${PUMPBOT_STRATEGY_HOLD_ONLY:-false}

# ⚡⚡ ULTRA-FAST MODE - Default and Only Mode
ultra_fast:
  # Core ultra-fast settings (always enabled)
  enabled: true
  skip_validation: ${PUMPBOT_ULTRA_FAST_SKIP_VALIDATION:-false}
  no_confirmation: ${PUMPBOT_ULTRA_FAST_NO_CONFIRMATION:-false}
  fire_and_forget: ${PUMPBOT_ULTRA_FAST_FIRE_AND_FORGET:-false}

  # Parallel processing for maximum speed
  parallel_workers: ${PUMPBOT_ULTRA_FAST_PARALLEL_WORKERS:-3}
  token_queue_size: ${PUMPBOT_ULTRA_FAST_TOKEN_QUEUE_SIZE:-100}

  # Performance optimizations
  cache_blockhash: ${PUMPBOT_ULTRA_FAST_CACHE_BLOCKHASH:-true}
  blockhash_refresh_interval: ${PUMPBOT_ULTRA_FAST_BLOCKHASH_INTERVAL:-10}
  precompute_instructions: ${PUMPBOT_ULTRA_FAST_PRECOMPUTE_INSTRUCTIONS:-true}
  rpc_timeout_ms: ${PUMPBOT_ULTRA_FAST_RPC_TIMEOUT_MS:-3000}

  # Performance monitoring
  benchmark_mode: ${PUMPBOT_ULTRA_FAST_BENCHMARK_MODE:-false}
  log_latency: ${PUMPBOT_ULTRA_FAST_LOG_LATENCY:-true}

  # Risk management for ultra-fast mode
  max_tokens_per_second: ${PUMPBOT_ULTRA_FAST_MAX_TOKENS_PER_SECOND:-10}
  emergency_stop_loss: ${PUMPBOT_ULTRA_FAST_EMERGENCY_STOP_LOSS:--50.0}
  fixed_buy_amount: ${PUMPBOT_ULTRA_FAST_FIXED_BUY_AMOUNT:-true}

  # Advanced optimizations (⚠️ DANGEROUS - use with caution!)
  skip_ata_creation: ${PUMPBOT_ULTRA_FAST_SKIP_ATA_CREATION:-false}
  assume_ata_exists: ${PUMPBOT_ULTRA_FAST_ASSUME_ATA_EXISTS:-false}
  immediate_execution: ${PUMPBOT_ULTRA_FAST_IMMEDIATE_EXECUTION:-true}
  priority_over_safety: ${PUMPBOT_ULTRA_FAST_PRIORITY_OVER_SAFETY:-false}

# JITO MEV Protection Settings
jito:
  enabled: ${PUMPBOT_JITO_ENABLED:-true}
  endpoint: "${PUMPBOT_JITO_ENDPOINT:-https://mainnet.block-engine.jito.wtf/api/v1/bundles}"
  api_key: "${PUMPBOT_JITO_API_KEY:-}"
  tip_amount: ${PUMPBOT_JITO_TIP_AMOUNT:-10000}
  use_for_trading: ${PUMPBOT_JITO_USE_FOR_TRADING:-true}
  confirm_timeout: ${PUMPBOT_JITO_CONFIRM_TIMEOUT:-30}
  max_bundle_size: ${PUMPBOT_JITO_MAX_BUNDLE_SIZE:-5}

# Logging settings
logging:
  level: "${PUMPBOT_LOGGING_LEVEL:-info}"
  format: "${PUMPBOT_LOGGING_FORMAT:-text}"
  log_to_file: ${PUMPBOT_LOGGING_LOG_TO_FILE:-false}
  log_file_path: "${PUMPBOT_LOGGING_LOG_FILE_PATH:-logs/bot.log}"
  trade_log_dir: "${PUMPBOT_LOGGING_TRADE_LOG_DIR:-trades}"

# Advanced settings
advanced:
  max_retries: ${PUMPBOT_ADVANCED_MAX_RETRIES:-3}
  retry_delay_ms: ${PUMPBOT_ADVANCED_RETRY_DELAY_MS:-1000}
  confirm_timeout_sec: ${PUMPBOT_ADVANCED_CONFIRM_TIMEOUT_SEC:-30}
  enable_metrics: ${PUMPBOT_ADVANCED_ENABLE_METRICS:-false}
  metrics_port: ${PUMPBOT_ADVANCED_METRICS_PORT:-8080}

# ========================================
# 🚀 NEW TRADING MODES EXAMPLES
# ========================================

# 🔰 TRADITIONAL SOL-BASED (Conservative):
# export PUMPBOT_TRADING_USE_TOKEN_AMOUNT="false"
# export PUMPBOT_TRADING_BUY_AMOUNT_SOL="0.01"
# export PUMPBOT_TRADING_AUTO_SELL="true"
# export PUMPBOT_TRADING_SELL_DELAY_MS="2000"

# ⚡ TOKEN-BASED ULTRA-FAST (Bypass Balance Checks):
# export PUMPBOT_TRADING_USE_TOKEN_AMOUNT="true"
# export PUMPBOT_TRADING_BUY_AMOUNT_TOKENS="5000000"
# export PUMPBOT_TRADING_AUTO_SELL="true"
# export PUMPBOT_TRADING_SELL_DELAY_MS="500"

# 🛡️ TOKEN-BASED + MEV PROTECTION:
# export PUMPBOT_TRADING_USE_TOKEN_AMOUNT="true"
# export PUMPBOT_TRADING_BUY_AMOUNT_TOKENS="3000000"
# export PUMPBOT_JITO_ENABLED="true"
# export PUMPBOT_JITO_USE_FOR_TRADING="true"
# export PUMPBOT_TRADING_SELL_DELAY_MS="1000"

# 💀 MAXIMUM SPEED (EXTREMELY RISKY):
# export PUMPBOT_TRADING_USE_TOKEN_AMOUNT="true"
# export PUMPBOT_TRADING_BUY_AMOUNT_TOKENS="10000000"
# export PUMPBOT_TRADING_SELL_DELAY_MS="100"
# export PUMPBOT_ULTRA_FAST_SKIP_VALIDATION="true"
# export PUMPBOT_ULTRA_FAST_PARALLEL_WORKERS="5"

# ========================================
# 📊 TIMING RECOMMENDATIONS
# ========================================

# SELL_DELAY_MS recommendations:
# 100-200ms:  Ultra-aggressive (very risky, might front-run yourself)
# 500-1000ms: Very fast (good for volatile tokens)
# 1000-2000ms: Fast (1-2 seconds, balanced)
# 3000-5000ms: Conservative (3-5 seconds, safer)
# 10000ms+:   Very conservative (10+ seconds)

# TOKEN_AMOUNT considerations:
# - Most tokens have 6-9 decimals
# - 1000000 = 1 token if 6 decimals
# - 5000000 = 5 tokens if 6 decimals
# - Check token decimals before setting amount
# - Token-based trading bypasses wallet balance checks

# ========================================
# ⚠️ WARNINGS FOR NEW FEATURES
# ========================================

# ⚠️ Auto-sell is now ENABLED BY DEFAULT
# ⚠️ Sell delay is now in MILLISECONDS (was seconds)
# ⚠️ Token-based trading bypasses balance validation
# ⚠️ Very short sell delays (100-200ms) are extremely risky
# ⚠️ Always test on devnet first with small amounts
# ⚠️ Monitor your trades closely with auto-sell enabled